### PR TITLE
Markdown file added following given template

### PR DESCRIPTION
**Pull request by agkeshav**

### CODE REVIEW

**Review by adviksinghania — CHANGES_REQUESTED** [review]
Hi Keshav, nice work. Can you please remove the square brackets? They're just placeholders.

**Comment by agkeshav** [comment]
> Hi Keshav, nice work. Can you please remove the square brackets? They're just placeholders.

ok I will

**Comment by agkeshav** [comment]
I have made the changes you can please check and merge my PR

**Review by adviksinghania — APPROVED** [review]
Nice work

**Pull request merged**
